### ISSUE TITLE
Anti-Missile Missiles fail to shoot down GtG missiles.

### ISSUE THREAD

**Issue by ColonelKai** [koiboi-dev/MissileWarfare#31]
## Description (Required)
Whenever the Anti-Missile Missile intercepts and detonates near a GtG missile, it fails to destroy it. The GtG missile continues on its normal course. 

## Steps to reproduce the Issue (Required)
1. Place an Anti-Missile Launcher and have it be filled with Anti-Missile Missiles.
2. Fire GtG missile.
3. Watch as the Anti-Missile intercepts the GtG.
4. The GtG continues its path.

## Expected behavior (Required)
For the GtG to detonate and cause no further damage.

## Server Log / Error Report
n/a

## Environment (Required)

 - Minecraft Version: git-Paper-387 (MC: 1.18.2)
 - Slimefun Version: RC - 32 (git e13d157a)
 - Plugin Version: v1.6.17

**Comment by ColonelKai** [comment]
caught error whilst testing.
```
[10:08:44 WARN]: [MissileWarfare] Task #39734 for MissileWarfare v1.6.17 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.remove()" because "this.armourStand" is null
        at me.kaiyan.missilewarfare.missiles.MissileController.explode(MissileController.java:326) ~[MissileWarfare v1.6.17.jar:?]
        at me.kaiyan.missilewarfare.missiles.MissileController.Update(MissileController.java:231) ~[MissileWarfare v1.6.17.jar:?]
        at me.kaiyan.missilewarfare.missiles.MissileController$2.run(MissileController.java:131) ~[MissileWarfare v1.6.17.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
